version: '2'
services:
  redis:
    image: redis:alpine
    networks:
      - internal
    restart: always
    volumes:
      - redis:/data

  postgres:
    image: postgres:9.5
    env_file:
      - ${PWD}/.local/postgres.env
    networks:
      - internal
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - 5432
    restart: on-failure:2

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: gauseng/superset:v0.15.0-production
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - internal
      - plant_secure
    external_links:
      - tpam_postgres_1:plant_secure_db
    volumes:
      - "assets:/env/lib/python3.5/site-packages/superset/static"
    environment:
      DEBUG: "True"
      SUPERSET_ENABLE_PROXY_FIX: "True"
      SUPERSET_AUTH_TYPE: "AUTH_REMOTE_USER"
      SECRET_KEY: thisISaSECRET_1234
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
    ports:
      - "8088:8088"
    command: "superset runserver -d"

volumes:
  dbdata:
    external: false
  redis:
    external: false
  assets:
    external: false

networks:
  internal:
    external: false
  plant_secure:
    external:
      name: tpam_internal
