version: '2'
services:
  redis:
    image: redis:alpine
    networks:
      - internal
    restart: always
    volumes:
      - redis:/data

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - internal
    ports:
      - "3306:3306"
    restart: always

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: gauseng/superset:v0.15.1-production
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - internal
      - plant_secure
    external_links:
      - plantsecure_postgres_1:plant_secure_db
    volumes:
      - "assets:/env/lib/python3.5/site-packages/superset/static"
    environment:
      DEBUG: "True"
      SUPERSET_ENABLE_PROXY_FIX: "True"
      SUPERSET_AUTH_TYPE: "AUTH_REMOTE_USER"
      SECRET_KEY: thisISaSECRET_1234
      SQLALCHEMY_DATABASE_URI: mysql://superset:superset@mysql:3306/superset
    ports:
      - "8088:8088"
    command: "superset runserver -d"

volumes:
  mysql:
    external: false
  redis:
    external: false
  assets:
    external: false

networks:
  internal:
    external: false
  plant_secure:
    external:
      name: plantsecure_internal
