version: '2'
services:
  redis:
    image: redis:alpine
    networks:
      - internal
    restart: always
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset
      MYSQL_USER: superset
      MYSQL_PASSWORD: superset
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: gauseng/superset:v0.14.1-production
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - internal
      - plant_secure_db
    environment:
      SUPERSET_ENABLE_PROXY_FIX: "True"
      SUPERSET_AUTH_TYPE: "AUTH_REMOTE_USER"
      #SUPERSET_PUBLIC_ROLE_LIKE_GAMMA: "True"
      #SUPERSET_ENABLE_CORS: "False"
      SECRET_KEY: thisISaSECRET_1234
      SQLALCHEMY_DATABASE_URI: mysql://superset:superset@mysql:3306/superset
      CACHE_CONFIG: "{\"CACHE_TYPE\": \"redis\", \"CACHE_DEFAULT_TIMEOUT\": 300, \"CACHE_KEY_PREFIX\": \"caravel_\", \"CACHE_REDIS_HOST\": \"redis\", \"CACHE_REDIS_PORT\": 6379, \"CACHE_REDIS_DB\": 1, \"CACHE_REDIS_URL\": \"redis://redis:6379/1\"}"
    ports:
      - "8088:8088"
    command: "superset runserver -d"
volumes:
  mysql:
    external: false
  redis:
    external: false

networks:
  internal:
    external: false
  plant_secure_db:
    external:
      name: tpam_internal
